import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "bn";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.browse": "Browse Media",
    "nav.categories": "Categories",
    "nav.contact": "Contact",
    "nav.creator": "Creator Portal",
    "nav.earnings": "$ Earnings",
    "nav.getApp": "Get App",
    "nav.login": "Login",
    "nav.signup": "Sign Up",
    "nav.dashboard": "Dashboard",
    "nav.profile": "Profile",
    "nav.logout": "Logout",
    "nav.account": "Account",
    "nav.theme": "Theme",
    "nav.softower": "Softower",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    
    // Homepage
    "home.title": "Free Stock Media",
    "home.subtitle": "For Everyone",
    "home.description": "Download unlimited videos, images, audio tracks, and templates completely free. No subscriptions, no watermarks, no restrictions.",
    "home.searchPlaceholder": "Search videos, images, audio...",
    "home.explore": "Explore",
    "home.trending": "Trending Now",
    "home.trendingSubtitle": "Most downloaded this week",
    "home.viewAll": "View All",
    "home.whyChoose": "Why Choose FreeMediaBuzz?",
    "home.whyChooseSubtitle": "Everything you need, absolutely free",
    "home.unlimitedDownloads": "Unlimited Downloads",
    "home.unlimitedDownloadsDesc": "Download as many files as you want, completely free. No restrictions, no limits.",
    "home.freeOpen": "100% Free & Open",
    "home.freeOpenDesc": "All media is free to use for personal and commercial projects. No subscriptions needed.",
    "home.highQuality": "High Quality",
    "home.highQualityDesc": "Professional-grade videos, images, audio, and templates from creators worldwide.",
    "home.easyToFind": "Easy to Find",
    "home.easyToFindDesc": "Powerful search with filters by category, format, resolution, and more.",
    "home.joinCreators": "Join 3.4M+ creators using FreeMediaBuzz",
    "home.mediaFiles": "Media Files",
    "home.activeUsers": "Active Users",
    "home.downloads": "Downloads",
    "home.freeForever": "Free Forever",
    "home.exploreByCategory": "Explore by Category",
    "home.findExactly": "Find exactly what you're looking for",
    "home.category.video": "Video",
    "home.category.images": "Images",
    "home.category.audio": "Audio",
    "home.category.templates": "Templates",
    "home.category.apk": "APK",
    "home.category.software": "Softower",
    "home.category.aivideogenerator": "AI Video Generator",
    "home.category.files": "files",
    "home.howItWorks": "How It Works",
    "home.howItWorksSubtitle": "Get your media in 3 simple steps",
    "home.step1": "Sign Up",
    "home.step1Desc": "Create a free account in seconds. No credit card required.",
    "home.step2": "Browse & Search",
    "home.step2Desc": "Explore our collection of videos, images, audio, and templates.",
    "home.step3": "Download & Use",
    "home.step3Desc": "Download what you need and use it freely in your projects.",
    "home.becomeCreator": "Become a Content Creator",
    "home.becomeCreatorDesc": "Join our community of creators and contribute your own media. Earn money through promotions and grow your portfolio.",
    "home.startCreating": "Start Creating",
    "home.readyToFind": "Ready to find your perfect media?",
    "home.startExploring": "Start exploring our collection of premium-quality free media today.",
    "home.browseMedia": "Browse Media",
    "home.createAccount": "Create Account",
    "home.loadingTrending": "Loading trending media...",
    "home.noTrending": "No trending media available",
    
    // AI Video Generator
    "aiVideoGenerator.title": "Generate Videos with AI",
    "aiVideoGenerator.description": "Transform your ideas into stunning videos with the power of artificial intelligence. Simply describe what you want, and we'll bring it to life.",
    "aiVideoGenerator.createVideo": "Create New Video",
    "aiVideoGenerator.formDescription": "Enter a detailed description of the video you want to generate",
    "aiVideoGenerator.promptLabel": "Video Prompt",
    "aiVideoGenerator.promptPlaceholder": "Example: A serene sunset over a calm ocean with gentle waves, cinematic style, 4K quality...",
    "aiVideoGenerator.promptHint": "Be as descriptive as possible. Include details about style, mood, colors, and any specific elements you want.",
    "aiVideoGenerator.durationLabel": "Duration (seconds)",
    "aiVideoGenerator.styleLabel": "Style",
    "aiVideoGenerator.styleRealistic": "Realistic",
    "aiVideoGenerator.styleCinematic": "Cinematic",
    "aiVideoGenerator.styleAnimated": "Animated",
    "aiVideoGenerator.styleArtistic": "Artistic",
    "aiVideoGenerator.styleAbstract": "Abstract",
    "aiVideoGenerator.aspectRatioLabel": "Aspect Ratio",
    "aiVideoGenerator.generating": "Generating...",
    "aiVideoGenerator.generateButton": "Generate Video",
    "aiVideoGenerator.history": "Your Generated Videos",
    "aiVideoGenerator.noVideos": "No videos generated yet",
    "aiVideoGenerator.noVideosDescription": "Create your first AI-generated video using the form above",
    "common.refresh": "Refresh",
    "common.preview": "Preview",
    "common.download": "Download",
    
    // User Manual
    "manual.title": "User Manual",
    "manual.subtitle": "How to Use FreeMediaBuzz",
    "manual.backToHome": "Back to Home",
    "manual.gettingStarted": "Getting Started",
    "manual.gettingStarted1": "1. Create an Account:",
    "manual.gettingStarted1Desc": "Click \"Sign Up\" in the top navigation to create your free account. No credit card required.",
    "manual.gettingStarted2": "2. Browse Media:",
    "manual.gettingStarted2Desc": "Use the search bar on the homepage or navigate to \"Browse Media\" to explore our collection of videos, images, audio, and templates.",
    "manual.gettingStarted3": "3. Search & Filter:",
    "manual.gettingStarted3Desc": "Use keywords to search for specific media. Filter by category, type, resolution, and more to find exactly what you need.",
    "manual.downloading": "Downloading Media",
    "manual.downloading1": "1. Select Media:",
    "manual.downloading1Desc": "Click on any media item to view its details page with preview, technical specifications, and usage rights.",
    "manual.downloading2": "2. Download:",
    "manual.downloading2Desc": "Click the \"Download Now\" button. You'll see a brief ad before your download starts - this helps us keep everything free!",
    "manual.downloading3": "3. Usage Rights:",
    "manual.downloading3Desc": "All media on FreeMediaBuzz is free for commercial use, requires no credit, and can be modified and redistributed.",
    "manual.categories": "Categories & Types",
    "manual.categoriesVideo": "Videos:",
    "manual.categoriesVideoDesc": "Stock footage in various resolutions (1080p, 4K, etc.) for your projects.",
    "manual.categoriesImages": "Images:",
    "manual.categoriesImagesDesc": "High-quality photos and graphics in multiple formats (JPG, PNG, etc.).",
    "manual.categoriesAudio": "Audio:",
    "manual.categoriesAudioDesc": "Music tracks and sound effects in MP3 and other audio formats.",
    "manual.categoriesTemplates": "Templates:",
    "manual.categoriesTemplatesDesc": "Design templates for various applications and platforms.",
    "manual.creator": "Become a Creator",
    "manual.creator1": "1. Creator Portal:",
    "manual.creator1Desc": "Access the Creator Portal from the navigation menu to upload and manage your media.",
    "manual.creator2": "2. Upload Media:",
    "manual.creator2Desc": "Share your videos, images, audio, or templates with the community.",
    "manual.creator3": "3. Earn Money:",
    "manual.creator3Desc": "Creators can earn through promotions and grow their portfolio on our platform.",
    "manual.earnings": "Earnings & Referrals",
    "manual.earnings1": "1. Referral System:",
    "manual.earnings1Desc": "Earn 100 coins for each person who signs up using your referral link. Access your referral link from the \"$ Earnings\" menu in the navigation.",
    "manual.earnings2": "2. Share Links:",
    "manual.earnings2Desc": "Create share links to earn coins. You can share normal links (earn 5-100 coins randomly per registration) or admin-approved posts (earn fixed coins per registration).",
    "manual.earnings3": "3. Track Earnings:",
    "manual.earnings3Desc": "View your total coins, referral coins, share coins, and available coins in the Earnings dashboard. Monitor your referral and share history to see all your earnings.",
    "manual.earnings4": "4. Withdraw Money:",
    "manual.earnings4Desc": "Convert your coins to real money! Minimum withdrawal is 5000 coins = 100 BDT. Withdrawals are processed via bKash. Submit a withdrawal request from the Earnings page and wait for admin approval.",
    "manual.earnings5": "5. Earnings Breakdown:",
    "manual.earnings5Referral": "Referral Coins: Earned when someone signs up using your referral link",
    "manual.earnings5Share": "Share Coins: Earned from sharing links (normal links or admin posts)",
    "manual.earnings5Available": "Available Coins: Total coins available for withdrawal",
    "manual.earnings5Pending": "Pending Withdraw: Coins waiting for admin approval",
    "manual.tips": "Tips & Best Practices",
    "manual.tips1": "• Use specific keywords when searching for better results",
    "manual.tips2": "• Check technical specifications before downloading to ensure compatibility",
    "manual.tips3": "• Save your favorite media using the \"Save\" button for quick access later",
    "manual.tips4": "• Share media with others using the \"Share\" button",
    "manual.tips5": "• Explore trending media to discover popular content",
    "manual.needHelp": "Need Help?",
    "manual.needHelpDesc": "If you have questions or need assistance, contact us at",
    
    // Footer
    "footer.userManual": "User Manual - How to Use FreeMediaBuzz",
    "footer.product": "Product",
    "footer.company": "Company",
    "footer.contact": "Contact",
    "footer.madeWith": "Made with",
    "footer.forCreators": "for creators everywhere",
    "footer.description": "Free stock media for creators, developers, and businesses. Download videos, images, audio, and templates without limits.",
    "footer.aboutUs": "About Us",
    "footer.blog": "Blog",
    "footer.careers": "Careers",
    "footer.email": "Email",
    "footer.address": "Address",
    "footer.globalHQ": "Global HQ",
  },
  bn: {
    // Navigation
    "nav.browse": "মিডিয়া ব্রাউজ করুন",
    "nav.categories": "ক্যাটাগরি",
    "nav.contact": "যোগাযোগ",
    "nav.creator": "ক্রিয়েটর পোর্টাল",
    "nav.earnings": "$ আয়",
    "nav.getApp": "অ্যাপ পান",
    "nav.login": "লগইন",
    "nav.signup": "সাইন আপ",
    "nav.dashboard": "ড্যাশবোর্ড",
    "nav.profile": "প্রোফাইল",
    "nav.logout": "লগআউট",
    "nav.account": "অ্যাকাউন্ট",
    "nav.theme": "থিম",
    "nav.softower": "সফটওয়ার",
    
    // Common
    "common.loading": "লোড হচ্ছে...",
    "common.error": "ত্রুটি",
    "common.success": "সফল",
    "common.cancel": "বাতিল",
    "common.save": "সংরক্ষণ",
    "common.delete": "মুছুন",
    "common.edit": "সম্পাদনা",
    "common.search": "খুঁজুন",
    "common.back": "পিছনে",
    "common.next": "পরবর্তী",
    "common.previous": "পূর্ববর্তী",
    "common.submit": "জমা দিন",
    
    // Homepage
    "home.title": "ফ্রি স্টক মিডিয়া",
    "home.subtitle": "সবার জন্য",
    "home.description": "সীমাহীন ভিডিও, ছবি, অডিও ট্র্যাক এবং টেমপ্লেট সম্পূর্ণ বিনামূল্যে ডাউনলোড করুন। কোন সাবস্ক্রিপশন নেই, কোন ওয়াটারমার্ক নেই, কোন সীমাবদ্ধতা নেই।",
    "home.searchPlaceholder": "ভিডিও, ছবি, অডিও খুঁজুন...",
    "home.explore": "অন্বেষণ করুন",
    "home.trending": "এখন ট্রেন্ডিং",
    "home.trendingSubtitle": "এই সপ্তাহে সবচেয়ে বেশি ডাউনলোড",
    "home.viewAll": "সব দেখুন",
    "home.whyChoose": "কেন FreeMediaBuzz বেছে নেবেন?",
    "home.whyChooseSubtitle": "আপনার যা প্রয়োজন সবই, সম্পূর্ণ বিনামূল্যে",
    "home.unlimitedDownloads": "সীমাহীন ডাউনলোড",
    "home.unlimitedDownloadsDesc": "যত খুশি ফাইল ডাউনলোড করুন, সম্পূর্ণ বিনামূল্যে। কোন সীমাবদ্ধতা নেই, কোন সীমা নেই।",
    "home.freeOpen": "১০০% বিনামূল্যে এবং উন্মুক্ত",
    "home.freeOpenDesc": "সমস্ত মিডিয়া ব্যক্তিগত এবং বাণিজ্যিক প্রকল্পে ব্যবহারের জন্য বিনামূল্যে। কোন সাবস্ক্রিপশন প্রয়োজন নেই।",
    "home.highQuality": "উচ্চ মান",
    "home.highQualityDesc": "বিশ্বজুড়ে ক্রিয়েটরদের কাছ থেকে পেশাদার-গ্রেড ভিডিও, ছবি, অডিও এবং টেমপ্লেট।",
    "home.easyToFind": "খুঁজে পাওয়া সহজ",
    "home.easyToFindDesc": "ক্যাটাগরি, ফরম্যাট, রেজোলিউশন এবং আরও অনেক কিছুর মাধ্যমে ফিল্টার সহ শক্তিশালী অনুসন্ধান।",
    "home.joinCreators": "FreeMediaBuzz ব্যবহার করে ৩.৪M+ ক্রিয়েটরের সাথে যোগ দিন",
    "home.mediaFiles": "মিডিয়া ফাইল",
    "home.activeUsers": "সক্রিয় ব্যবহারকারী",
    "home.downloads": "ডাউনলোড",
    "home.freeForever": "চিরকাল বিনামূল্যে",
    "home.exploreByCategory": "ক্যাটাগরি অনুযায়ী অন্বেষণ করুন",
    "home.findExactly": "আপনি যা খুঁজছেন তা সঠিকভাবে খুঁজে পান",
    "home.category.video": "ভিডিও",
    "home.category.images": "ছবি",
    "home.category.audio": "অডিও",
    "home.category.templates": "টেমপ্লেট",
    "home.category.apk": "APK",
    "home.category.software": "সফটওয়ার",
    "home.category.aivideogenerator": "AI ভিডিও জেনারেটর",
    "home.category.files": "ফাইল",
    "home.howItWorks": "এটি কীভাবে কাজ করে",
    "home.howItWorksSubtitle": "৩টি সহজ ধাপে আপনার মিডিয়া পান",
    "home.step1": "সাইন আপ",
    "home.step1Desc": "সেকেন্ডে একটি বিনামূল্যে অ্যাকাউন্ট তৈরি করুন। কোন ক্রেডিট কার্ড প্রয়োজন নেই।",
    "home.step2": "ব্রাউজ এবং অনুসন্ধান",
    "home.step2Desc": "আমাদের ভিডিও, ছবি, অডিও এবং টেমপ্লেটের সংগ্রহ অন্বেষণ করুন।",
    "home.step3": "ডাউনলোড এবং ব্যবহার",
    "home.step3Desc": "আপনার যা প্রয়োজন তা ডাউনলোড করুন এবং আপনার প্রকল্পে অবাধে ব্যবহার করুন।",
    "home.becomeCreator": "কন্টেন্ট ক্রিয়েটর হন",
    "home.becomeCreatorDesc": "আমাদের ক্রিয়েটর সম্প্রদায়ে যোগ দিন এবং আপনার নিজের মিডিয়া অবদান রাখুন। প্রচারের মাধ্যমে অর্থ উপার্জন করুন এবং আপনার পোর্টফোলিও বৃদ্ধি করুন।",
    "home.startCreating": "তৈরি করা শুরু করুন",
    "home.readyToFind": "আপনার নিখুঁত মিডিয়া খুঁজে পাওয়ার জন্য প্রস্তুত?",
    "home.startExploring": "আজই আমাদের প্রিমিয়াম-মানের বিনামূল্যে মিডিয়ার সংগ্রহ অন্বেষণ শুরু করুন।",
    "home.browseMedia": "মিডিয়া ব্রাউজ করুন",
    "home.createAccount": "অ্যাকাউন্ট তৈরি করুন",
    "home.loadingTrending": "ট্রেন্ডিং মিডিয়া লোড হচ্ছে...",
    "home.noTrending": "কোন ট্রেন্ডিং মিডিয়া পাওয়া যায়নি",
    
    // AI Video Generator
    "aiVideoGenerator.title": "AI দিয়ে ভিডিও তৈরি করুন",
    "aiVideoGenerator.description": "কৃত্রিম বুদ্ধিমত্তার শক্তিতে আপনার ধারণাগুলিকে চমৎকার ভিডিওতে রূপান্তর করুন। আপনি যা চান তা বর্ণনা করুন, আমরা এটিকে জীবন্ত করে তুলব।",
    "aiVideoGenerator.createVideo": "নতুন ভিডিও তৈরি করুন",
    "aiVideoGenerator.formDescription": "আপনি যে ভিডিও তৈরি করতে চান তার বিস্তারিত বিবরণ লিখুন",
    "aiVideoGenerator.promptLabel": "ভিডিও প্রম্পট",
    "aiVideoGenerator.promptPlaceholder": "উদাহরণ: শান্ত সমুদ্রের উপরে একটি প্রশান্ত সূর্যাস্ত, মৃদু তরঙ্গ সহ, সিনেম্যাটিক শৈলী, 4K মানের...",
    "aiVideoGenerator.promptHint": "যতটা সম্ভব বর্ণনামূলক হন। শৈলী, মেজাজ, রঙ এবং যে কোন নির্দিষ্ট উপাদান সম্পর্কে বিবরণ অন্তর্ভুক্ত করুন।",
    "aiVideoGenerator.durationLabel": "কালকাল (সেকেন্ড)",
    "aiVideoGenerator.styleLabel": "শৈলী",
    "aiVideoGenerator.styleRealistic": "বাস্তবসম্মত",
    "aiVideoGenerator.styleCinematic": "সিনেম্যাটিক",
    "aiVideoGenerator.styleAnimated": "অ্যানিমেটেড",
    "aiVideoGenerator.styleArtistic": "শৈল্পিক",
    "aiVideoGenerator.styleAbstract": "অমূর্ত",
    "aiVideoGenerator.aspectRatioLabel": "দৃশ্যমান অনুপাত",
    "aiVideoGenerator.generating": "তৈরি হচ্ছে...",
    "aiVideoGenerator.generateButton": "ভিডিও তৈরি করুন",
    "aiVideoGenerator.history": "আপনার তৈরি করা ভিডিও",
    "aiVideoGenerator.noVideos": "এখনও কোন ভিডিও তৈরি হয়নি",
    "aiVideoGenerator.noVideosDescription": "উপরের ফর্ম ব্যবহার করে আপনার প্রথম AI-তৈরি ভিডিও তৈরি করুন",
    "common.refresh": "রিফ্রেশ",
    "common.preview": "পূর্বাবলোকন",
    "common.download": "ডাউনলোড",
    
    // User Manual
    "manual.title": "ব্যবহারকারী ম্যানুয়াল",
    "manual.subtitle": "কীভাবে FreeMediaBuzz ব্যবহার করবেন",
    "manual.backToHome": "হোমে ফিরুন",
    "manual.gettingStarted": "শুরু করা",
    "manual.gettingStarted1": "১. অ্যাকাউন্ট তৈরি করুন:",
    "manual.gettingStarted1Desc": "শীর্ষ নেভিগেশনে \"সাইন আপ\" ক্লিক করে আপনার বিনামূল্যে অ্যাকাউন্ট তৈরি করুন। কোন ক্রেডিট কার্ড প্রয়োজন নেই।",
    "manual.gettingStarted2": "২. মিডিয়া ব্রাউজ করুন:",
    "manual.gettingStarted2Desc": "হোমপেজে সার্চ বার ব্যবহার করুন বা \"মিডিয়া ব্রাউজ করুন\" এ নেভিগেট করুন আমাদের ভিডিও, ছবি, অডিও এবং টেমপ্লেটের সংগ্রহ অন্বেষণ করতে।",
    "manual.gettingStarted3": "৩. অনুসন্ধান এবং ফিল্টার:",
    "manual.gettingStarted3Desc": "নির্দিষ্ট মিডিয়া খুঁজতে কীওয়ার্ড ব্যবহার করুন। ক্যাটাগরি, প্রকার, রেজোলিউশন এবং আরও অনেক কিছুর মাধ্যমে ফিল্টার করুন আপনার প্রয়োজনীয় জিনিসটি খুঁজে পেতে।",
    "manual.downloading": "মিডিয়া ডাউনলোড করা",
    "manual.downloading1": "১. মিডিয়া নির্বাচন করুন:",
    "manual.downloading1Desc": "যেকোনো মিডিয়া আইটেমে ক্লিক করুন এর বিস্তারিত পৃষ্ঠা দেখতে, যেখানে প্রিভিউ, প্রযুক্তিগত বিবরণ এবং ব্যবহারের অধিকার রয়েছে।",
    "manual.downloading2": "২. ডাউনলোড:",
    "manual.downloading2Desc": "\"এখনই ডাউনলোড করুন\" বাটনে ক্লিক করুন। আপনার ডাউনলোড শুরু হওয়ার আগে আপনি একটি সংক্ষিপ্ত বিজ্ঞাপন দেখবেন - এটি আমাদের সবকিছু বিনামূল্যে রাখতে সাহায্য করে!",
    "manual.downloading3": "৩. ব্যবহারের অধিকার:",
    "manual.downloading3Desc": "FreeMediaBuzz-এ সমস্ত মিডিয়া বাণিজ্যিক ব্যবহারের জন্য বিনামূল্যে, কোন ক্রেডিট প্রয়োজন নেই, এবং এটি পরিবর্তন এবং পুনরায় বিতরণ করা যেতে পারে।",
    "manual.categories": "ক্যাটাগরি এবং প্রকার",
    "manual.categoriesVideo": "ভিডিও:",
    "manual.categoriesVideoDesc": "বিভিন্ন রেজোলিউশনে স্টক ফুটেজ (১০৮০পি, ৪কে, ইত্যাদি) আপনার প্রকল্পের জন্য।",
    "manual.categoriesImages": "ছবি:",
    "manual.categoriesImagesDesc": "বিভিন্ন ফরম্যাটে (JPG, PNG, ইত্যাদি) উচ্চ-মানের ফটো এবং গ্রাফিক্স।",
    "manual.categoriesAudio": "অডিও:",
    "manual.categoriesAudioDesc": "MP3 এবং অন্যান্য অডিও ফরম্যাটে সঙ্গীত ট্র্যাক এবং সাউন্ড ইফেক্ট।",
    "manual.categoriesTemplates": "টেমপ্লেট:",
    "manual.categoriesTemplatesDesc": "বিভিন্ন অ্যাপ্লিকেশন এবং প্ল্যাটফর্মের জন্য ডিজাইন টেমপ্লেট।",
    "manual.creator": "ক্রিয়েটর হন",
    "manual.creator1": "১. ক্রিয়েটর পোর্টাল:",
    "manual.creator1Desc": "নেভিগেশন মেনু থেকে ক্রিয়েটর পোর্টাল অ্যাক্সেস করুন আপনার মিডিয়া আপলোড এবং পরিচালনা করতে।",
    "manual.creator2": "২. মিডিয়া আপলোড করুন:",
    "manual.creator2Desc": "সম্প্রদায়ের সাথে আপনার ভিডিও, ছবি, অডিও বা টেমপ্লেট শেয়ার করুন।",
    "manual.creator3": "৩. অর্থ উপার্জন করুন:",
    "manual.creator3Desc": "ক্রিয়েটররা প্রচারের মাধ্যমে অর্থ উপার্জন করতে পারে এবং আমাদের প্ল্যাটফর্মে তাদের পোর্টফোলিও বৃদ্ধি করতে পারে।",
    "manual.earnings": "আয় এবং রেফারেল",
    "manual.earnings1": "১. রেফারেল সিস্টেম:",
    "manual.earnings1Desc": "আপনার রেফারেল লিঙ্ক ব্যবহার করে সাইন আপ করা প্রতিটি ব্যক্তির জন্য ১০০ কয়েন উপার্জন করুন। নেভিগেশনে \"$ আয়\" মেনু থেকে আপনার রেফারেল লিঙ্ক অ্যাক্সেস করুন।",
    "manual.earnings2": "২. শেয়ার লিঙ্ক:",
    "manual.earnings2Desc": "কয়েন উপার্জনের জন্য শেয়ার লিঙ্ক তৈরি করুন। আপনি সাধারণ লিঙ্ক শেয়ার করতে পারেন (রেজিস্ট্রেশন প্রতি ৫-১০০ কয়েন এলোমেলোভাবে উপার্জন) বা অ্যাডমিন-অনুমোদিত পোস্ট (রেজিস্ট্রেশন প্রতি নির্দিষ্ট কয়েন উপার্জন)।",
    "manual.earnings3": "৩. আয় ট্র্যাক করুন:",
    "manual.earnings3Desc": "আয় ড্যাশবোর্ডে আপনার মোট কয়েন, রেফারেল কয়েন, শেয়ার কয়েন এবং উপলব্ধ কয়েন দেখুন। আপনার রেফারেল এবং শেয়ার ইতিহাস পর্যবেক্ষণ করুন আপনার সমস্ত আয় দেখতে।",
    "manual.earnings4": "৪. অর্থ উত্তোলন:",
    "manual.earnings4Desc": "আপনার কয়েনকে আসল টাকায় রূপান্তর করুন! সর্বনিম্ন উত্তোলন হল ৫০০০ কয়েন = ১০০ টাকা। উত্তোলন bKash-এর মাধ্যমে প্রক্রিয়া করা হয়। আয় পৃষ্ঠা থেকে একটি উত্তোলন অনুরোধ জমা দিন এবং অ্যাডমিন অনুমোদনের জন্য অপেক্ষা করুন।",
    "manual.earnings5": "৫. আয়ের বিভাজন:",
    "manual.earnings5Referral": "রেফারেল কয়েন: কেউ আপনার রেফারেল লিঙ্ক ব্যবহার করে সাইন আপ করলে উপার্জিত",
    "manual.earnings5Share": "শেয়ার কয়েন: লিঙ্ক শেয়ার করার মাধ্যমে উপার্জিত (সাধারণ লিঙ্ক বা অ্যাডমিন পোস্ট)",
    "manual.earnings5Available": "উপলব্ধ কয়েন: উত্তোলনের জন্য মোট কয়েন",
    "manual.earnings5Pending": "বিচারাধীন উত্তোলন: অ্যাডমিন অনুমোদনের জন্য অপেক্ষারত কয়েন",
    "manual.tips": "টিপস এবং সেরা অনুশীলন",
    "manual.tips1": "• ভাল ফলাফলের জন্য অনুসন্ধান করার সময় নির্দিষ্ট কীওয়ার্ড ব্যবহার করুন",
    "manual.tips2": "• সামঞ্জস্যতা নিশ্চিত করতে ডাউনলোড করার আগে প্রযুক্তিগত বিবরণ পরীক্ষা করুন",
    "manual.tips3": "• পরে দ্রুত অ্যাক্সেসের জন্য \"সংরক্ষণ\" বাটন ব্যবহার করে আপনার প্রিয় মিডিয়া সংরক্ষণ করুন",
    "manual.tips4": "• \"শেয়ার\" বাটন ব্যবহার করে অন্যদের সাথে মিডিয়া শেয়ার করুন",
    "manual.tips5": "• জনপ্রিয় কন্টেন্ট আবিষ্কার করতে ট্রেন্ডিং মিডিয়া অন্বেষণ করুন",
    "manual.needHelp": "সাহায্য প্রয়োজন?",
    "manual.needHelpDesc": "যদি আপনার কোন প্রশ্ন থাকে বা সহায়তার প্রয়োজন হয়, আমাদের সাথে যোগাযোগ করুন",
    
    // Footer
    "footer.userManual": "ব্যবহারকারী ম্যানুয়াল - কীভাবে FreeMediaBuzz ব্যবহার করবেন",
    "footer.product": "পণ্য",
    "footer.company": "কোম্পানি",
    "footer.contact": "যোগাযোগ",
    "footer.madeWith": "তৈরি হয়েছে",
    "footer.forCreators": "সব ক্রিয়েটরের জন্য",
    "footer.description": "ক্রিয়েটর, ডেভেলপার এবং ব্যবসার জন্য বিনামূল্যে স্টক মিডিয়া। সীমা ছাড়াই ভিডিও, ছবি, অডিও এবং টেমপ্লেট ডাউনলোড করুন।",
    "footer.aboutUs": "আমাদের সম্পর্কে",
    "footer.blog": "ব্লগ",
    "footer.careers": "ক্যারিয়ার",
    "footer.email": "ইমেইল",
    "footer.address": "ঠিকানা",
    "footer.globalHQ": "গ্লোবাল HQ",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Get language from localStorage or default to English
    const saved = localStorage.getItem("language") as Language;
    return saved && (saved === "en" || saved === "bn") ? saved : "en";
  });

  useEffect(() => {
    // Save language preference to localStorage
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

